/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package newpackage;

/**
 *
 * @author ALUNO
 */
public class jantaUsuario extends javax.swing.JFrame {

    /**
     * Creates new form jantaUsuario
     */
    public jantaUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        EntradaAdicional = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        EntradaJantinha = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        SaidaJantinha = new javax.swing.JTextPane();
        BotEmitir = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        SaidaValorFinal = new javax.swing.JTextPane();
        jbuttonLimpar = new javax.swing.JButton();
        btnConfig = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("iJanta");

        EntradaAdicional.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        EntradaAdicional.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "REFRIGERANTE 350ml", "REFRIGERANTE 600ml", "REFRIGERANTE 2L", "CERVEJA LITRO", "CACHAÇA PÍTU" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        EntradaAdicional.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EntradaAdicionalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(EntradaAdicional);

        EntradaJantinha.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        EntradaJantinha.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "JANTINHA 1", "JANTINHA 2", "JANTINHA 3", "JANTINHA 4" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        EntradaJantinha.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EntradaJantinhaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(EntradaJantinha);

        SaidaJantinha.setEditable(false);
        SaidaJantinha.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jScrollPane4.setViewportView(SaidaJantinha);

        BotEmitir.setText("Emitir");

        SaidaValorFinal.setEditable(false);
        jScrollPane5.setViewportView(SaidaValorFinal);

        jbuttonLimpar.setText("Limpar");
        jbuttonLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbuttonLimparMouseClicked(evt);
            }
        });
        jbuttonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonLimparActionPerformed(evt);
            }
        });

        btnConfig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfigActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jbuttonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5)
                    .addComponent(jScrollPane4)
                    .addComponent(BotEmitir, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2)))
                .addGap(16, 16, 16)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotEmitir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbuttonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(240, 75, 4));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 185, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 592, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EntradaAdicionalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntradaAdicionalMouseClicked
              
        int auxadicional,c;
        
        // pega o valor de index
        auxadicional = EntradaAdicional.getAnchorSelectionIndex();
        
        endadicional = "";
        
        
        if(saidaadicional[auxadicional] == null){
            
            //Adicionar itens a comanda de venda
            
            if(auxadicional == 0){
                ContadorAdicional[auxadicional] = 1;
            saidaadicional[auxadicional] = "Coca cola 350";}
            if(auxadicional == 1){
                ContadorAdicional[auxadicional] = 1;
            saidaadicional[auxadicional] = "Coca cola 600";}
            if(auxadicional == 2){
                ContadorAdicional[auxadicional] = 1;
            saidaadicional[auxadicional] = "Coca cola 2L";}
            if(auxadicional == 3){
                ContadorAdicional[auxadicional] = 1;
            saidaadicional[auxadicional] = "Cerveja LITRO";}
            if(auxadicional == 4){
                ContadorAdicional[auxadicional] = 1;
            saidaadicional[auxadicional] = "CACHAÇA PÍTU";}
            
            
            
        }else{
            
            ContadorAdicional[auxadicional] = ContadorAdicional[auxadicional] + 1;
        }
        
        
        // for para gerar a String de saida com os valores previamente gerados
        for(c=0;c<10;c++){
            
            if(saidaadicional[c] != null){
                
                endadicional = endadicional + saidaadicional[c]+ "("+ContadorAdicional[c]+")" + "\n";
                
        }}
        SaidaFinal1 = endjantinha + endadicional;
        
        SaidaJantinha.setText(SaidaFinal1);
        
        
        ValorFinalSaida = (ValorJantinha[1] * ContadorJantinha[1])+(ValorJantinha[2] * ContadorJantinha[2])+(ValorJantinha[3] * ContadorJantinha[3])+(ValorJantinha[4] * ContadorJantinha[4])+(ValorExtra[1]*ContadorAdicional[1])+(ValorExtra[2]*ContadorAdicional[2])+(ValorExtra[3]*ContadorAdicional[3])+(ValorExtra[4]*ContadorAdicional[4]);
        String ValorFinalSaidaString = Float.toString(ValorFinalSaida);
        SaidaValorFinal.setText(ValorFinalSaidaString);
        
        
        
        
        
        
                


        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaAdicionalMouseClicked

        LayoutTrabalho aux = new LayoutTrabalho();
        
        float[] ValorJantinha =LayoutTrabalho.ValorPrato;
        float[] ValorExtra=LayoutTrabalho.ValorExtra;
    
        String SaidaFinal1;
        
        float ValorFinalSaida;
    private void EntradaJantinhaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EntradaJantinhaMouseClicked

        int aux,c;
        aux = EntradaJantinha.getAnchorSelectionIndex();
        
        endjantinha = "";
        
        
        if(saidajantinha[aux] == null){
            
            ContadorJantinha[aux] = 1;
            saidajantinha[aux] = "Jantinha "+(aux + 1)+" ";
            
        }else{
            
            ContadorJantinha[aux] = ContadorJantinha[aux] + 1;
        }
        
        
        for(c=0;c<10;c++){
            
            if(saidajantinha[c] != null){
                
                endjantinha = endjantinha + saidajantinha[c]+ "("+ContadorJantinha[c]+")" + "\n";
                
        }}
        
        
        SaidaFinal1 = endadicional + endjantinha;
        
        SaidaJantinha.setText(SaidaFinal1);
        
        
        ValorFinalSaida = (ValorJantinha[1] * ContadorJantinha[1])+(ValorJantinha[2] * ContadorJantinha[2])+(ValorJantinha[3] * ContadorJantinha[3])+(ValorJantinha[4] * ContadorJantinha[4])+(ValorExtra[1]*ContadorAdicional[1])+(ValorExtra[2]*ContadorAdicional[2])+(ValorExtra[3]*ContadorAdicional[3])+(ValorExtra[4]*ContadorAdicional[4]);
        String ValorFinalSaidaString = Float.toString(ValorFinalSaida);
        SaidaValorFinal.setText(ValorFinalSaidaString);
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        

        // TODO add your handling code here:
    }//GEN-LAST:event_EntradaJantinhaMouseClicked

    private void jbuttonLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbuttonLimparMouseClicked
    
    
















// TODO add your handling code here:
    }//GEN-LAST:event_jbuttonLimparMouseClicked

    private void jbuttonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonLimparActionPerformed
    int c;
    
    
        for(c = 0;c < ContadorJantinha.length; c++){       
            ContadorJantinha[c] = 0;}
        for(c = 0;c < ContadorAdicional.length; c++){       
            ContadorAdicional[c] = 0;} 
        for(c = 0;c < saidajantinha.length; c++){       
            saidajantinha[c] = null;} 
        for(c = 0;c < saidaadicional.length; c++){       
            saidaadicional[c] = null;} 
        for(c = 0;c < SaidaFinal.length; c++){       
            SaidaFinal[c] = "";} 
        
        endjantinha= "";
        endadicional= "";
        
        SaidaJantinha.setText(endjantinha);
     


















// TODO add your handling code here:
     
    }//GEN-LAST:event_jbuttonLimparActionPerformed

    private void btnConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfigActionPerformed
        // TODO add your handling code here:
        if(evt.getSource()==btnConfig) {
        LayoutTrabalho LayoutTrabalho = new LayoutTrabalho();
        LayoutTrabalho.setVisible(true);
        }
    }//GEN-LAST:event_btnConfigActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        int[] ContadorJantinha = new int[10];
        
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jantaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jantaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jantaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jantaUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jantaUsuario().setVisible(true);
            }
        });
    }
    
    
    
    
    int[] ContadorJantinha = new int[10];
    int[] ContadorAdicional = new int[10];
    String[] saidajantinha = new String[10];
    String[] saidaadicional = new String[10];
    String[] SaidaFinal = new String[10];
    String endjantinha, endadicional;
    int limpar = 1;
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotEmitir;
    private javax.swing.JList<String> EntradaAdicional;
    private javax.swing.JList<String> EntradaJantinha;
    private javax.swing.JTextPane SaidaJantinha;
    private javax.swing.JTextPane SaidaValorFinal;
    private javax.swing.JButton btnConfig;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton jbuttonLimpar;
    // End of variables declaration//GEN-END:variables
}
