/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pacotetrabalho;

/**
 *
 * @author felip
 */
public class TelaJogoVelha extends javax.swing.JFrame {

    /**
     * Creates new form TelaJogoVelha
     */
    public TelaJogoVelha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bot12 = new javax.swing.JButton();
        Bot13 = new javax.swing.JButton();
        Bot11 = new javax.swing.JButton();
        Bot23 = new javax.swing.JButton();
        Bot21 = new javax.swing.JButton();
        Bot22 = new javax.swing.JButton();
        Bot33 = new javax.swing.JButton();
        Bot31 = new javax.swing.JButton();
        Bot32 = new javax.swing.JButton();
        Saida = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        SaidaResultado = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(350, 370));

        Bot12.setBackground(new java.awt.Color(0, 0, 102));
        Bot12.setFont(new java.awt.Font("Segoe UI", 0, 80)); // NOI18N
        Bot12.setPreferredSize(new java.awt.Dimension(100, 100));
        Bot12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot12ActionPerformed(evt);
            }
        });

        Bot13.setBackground(new java.awt.Color(0, 0, 102));
        Bot13.setFont(new java.awt.Font("Segoe UI", 0, 80)); // NOI18N
        Bot13.setPreferredSize(new java.awt.Dimension(100, 100));
        Bot13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot13ActionPerformed(evt);
            }
        });

        Bot11.setBackground(new java.awt.Color(0, 0, 102));
        Bot11.setFont(new java.awt.Font("Segoe UI", 0, 80)); // NOI18N
        Bot11.setPreferredSize(new java.awt.Dimension(100, 100));
        Bot11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot11ActionPerformed(evt);
            }
        });

        Bot23.setBackground(new java.awt.Color(0, 0, 102));
        Bot23.setFont(new java.awt.Font("Segoe UI", 0, 80)); // NOI18N
        Bot23.setPreferredSize(new java.awt.Dimension(100, 100));
        Bot23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot23ActionPerformed(evt);
            }
        });

        Bot21.setBackground(new java.awt.Color(0, 0, 102));
        Bot21.setFont(new java.awt.Font("Segoe UI", 0, 80)); // NOI18N
        Bot21.setPreferredSize(new java.awt.Dimension(100, 100));
        Bot21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot21ActionPerformed(evt);
            }
        });

        Bot22.setBackground(new java.awt.Color(0, 0, 102));
        Bot22.setFont(new java.awt.Font("Segoe UI", 0, 80)); // NOI18N
        Bot22.setPreferredSize(new java.awt.Dimension(100, 100));
        Bot22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot22ActionPerformed(evt);
            }
        });

        Bot33.setBackground(new java.awt.Color(0, 0, 102));
        Bot33.setFont(new java.awt.Font("Segoe UI", 0, 80)); // NOI18N
        Bot33.setPreferredSize(new java.awt.Dimension(100, 100));
        Bot33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot33ActionPerformed(evt);
            }
        });

        Bot31.setBackground(new java.awt.Color(0, 0, 102));
        Bot31.setFont(new java.awt.Font("Segoe UI", 0, 80)); // NOI18N
        Bot31.setPreferredSize(new java.awt.Dimension(100, 100));
        Bot31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot31ActionPerformed(evt);
            }
        });

        Bot32.setBackground(new java.awt.Color(0, 0, 102));
        Bot32.setFont(new java.awt.Font("Segoe UI", 0, 80)); // NOI18N
        Bot32.setPreferredSize(new java.awt.Dimension(100, 100));
        Bot32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Bot32ActionPerformed(evt);
            }
        });

        SaidaResultado.setColumns(20);
        SaidaResultado.setRows(5);
        jScrollPane1.setViewportView(SaidaResultado);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Bot31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Bot32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Bot33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Bot21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Bot22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Bot23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Bot11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Bot12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Bot13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(85, 85, 85)
                        .addComponent(Saida, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(233, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Bot11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bot13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Bot12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(Saida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bot21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bot23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bot22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Bot31, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bot33, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Bot32, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Bot13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot13ActionPerformed
    if(MatJV[0][2] == 0 && endgame == 0){
            if(userad != 0){           
                MatJV[0][2] = 1;
                Bot13.setText("X");
                user++;}
            if(userad == 0){
                MatJV[0][2] = 2;
                Bot13.setText("O");
                user++;}
            
                userad = user % 2;
            
                if(MatJV[0][0] == 1&& MatJV[0][1] == 1&& MatJV[0][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[1][0] == 1&& MatJV[1][1] == 1&& MatJV[1][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[2][0] == 1&& MatJV[2][1] == 1&& MatJV[2][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[0][0] == 1&& MatJV[1][0] == 1&& MatJV[2][0] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[0][1] == 1&& MatJV[1][1] == 1&& MatJV[2][1] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[0][2] == 1&& MatJV[1][2] == 1&& MatJV[2][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[0][0] == 1&& MatJV[1][1] == 1&& MatJV[2][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[2][0] == 1&& MatJV[1][1] == 1&& MatJV[0][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                
                if(MatJV[0][0] == 1&& MatJV[0][1] == 1&& MatJV[0][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[1][0] == 1&& MatJV[1][1] == 1&& MatJV[1][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[2][0] == 1&& MatJV[2][1] == 1&& MatJV[2][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[0][0] == 1&& MatJV[1][0] == 1&& MatJV[2][0] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[0][1] == 1&& MatJV[1][1] == 1&& MatJV[2][1] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[0][2] == 1&& MatJV[1][2] == 1&& MatJV[2][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[0][0] == 1&& MatJV[1][1] == 1&& MatJV[2][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[2][0] == 1&& MatJV[1][1] == 1&& MatJV[0][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
            
        }


// TODO add your handling code here:
    }//GEN-LAST:event_Bot13ActionPerformed

    private void Bot23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot23ActionPerformed
    if(MatJV[1][2] == 0 && endgame == 0){
            if(userad != 0 && endgame == 0){           
                MatJV[1][2] = 1;
                Bot23.setText("X");
                user++;}
            if(userad == 0){
                MatJV[1][2] = 2;
                Bot23.setText("O");
                user++;}
            
                userad = user % 2;
                
                if(MatJV[0][0] == 1&& MatJV[0][1] == 1&& MatJV[0][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[1][0] == 1&& MatJV[1][1] == 1&& MatJV[1][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[2][0] == 1&& MatJV[2][1] == 1&& MatJV[2][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[0][0] == 1&& MatJV[1][0] == 1&& MatJV[2][0] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[0][1] == 1&& MatJV[1][1] == 1&& MatJV[2][1] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[0][2] == 1&& MatJV[1][2] == 1&& MatJV[2][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[0][0] == 1&& MatJV[1][1] == 1&& MatJV[2][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[2][0] == 1&& MatJV[1][1] == 1&& MatJV[0][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                
                if(MatJV[0][0] == 1&& MatJV[0][1] == 1&& MatJV[0][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[1][0] == 1&& MatJV[1][1] == 1&& MatJV[1][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[2][0] == 1&& MatJV[2][1] == 1&& MatJV[2][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[0][0] == 1&& MatJV[1][0] == 1&& MatJV[2][0] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[0][1] == 1&& MatJV[1][1] == 1&& MatJV[2][1] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[0][2] == 1&& MatJV[1][2] == 1&& MatJV[2][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[0][0] == 1&& MatJV[1][1] == 1&& MatJV[2][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[2][0] == 1&& MatJV[1][1] == 1&& MatJV[0][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");}
            
        }    // TODO add your handling code here:
    }//GEN-LAST:event_Bot23ActionPerformed

    private void Bot33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot33ActionPerformed
    if(MatJV[2][2] == 0 && endgame == 0){
            if(userad != 0){           
                MatJV[2][2] = 1;
                Bot33.setText("X");
                user++;}
            if(userad == 0){
                MatJV[2][2] = 2;
                Bot33.setText("O");
                user++;}
            
                userad = user % 2;
            
                if(MatJV[0][0] == 1&& MatJV[0][1] == 1&& MatJV[0][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[1][0] == 1&& MatJV[1][1] == 1&& MatJV[1][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[2][0] == 1&& MatJV[2][1] == 1&& MatJV[2][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[0][0] == 1&& MatJV[1][0] == 1&& MatJV[2][0] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[0][1] == 1&& MatJV[1][1] == 1&& MatJV[2][1] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[0][2] == 1&& MatJV[1][2] == 1&& MatJV[2][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[0][0] == 1&& MatJV[1][1] == 1&& MatJV[2][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[2][0] == 1&& MatJV[1][1] == 1&& MatJV[0][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                
                if(MatJV[0][0] == 2&& MatJV[0][1] == 2&& MatJV[0][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[1][0] == 2&& MatJV[1][1] == 2&& MatJV[1][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[2][0] == 2&& MatJV[2][1] == 2&& MatJV[2][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[0][0] == 2&& MatJV[1][0] == 2&& MatJV[2][0] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[0][1] == 2&& MatJV[1][1] == 2&& MatJV[2][1] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[0][2] == 2&& MatJV[1][2] == 2&& MatJV[2][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[0][0] == 2&& MatJV[1][1] == 2&& MatJV[2][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[2][0] == 2&& MatJV[1][1] == 2&& MatJV[0][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
            
        }    // TODO add your handling code here:
    }//GEN-LAST:event_Bot33ActionPerformed

    private void Bot11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot11ActionPerformed
        // TODO add your handling code here:
        
        
        
        if(MatJV[0][0] == 0 && endgame == 0){
            if(userad != 0){           
                MatJV[0][0] = 1;
                Bot11.setText("X");
                user++;}
            if(userad == 0){
                MatJV[0][0] = 2;
                Bot11.setText("O");
                user++;}
            
                userad = user % 2;
          
                if(MatJV[0][0] == 1&& MatJV[0][1] == 1&& MatJV[0][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[1][0] == 1&& MatJV[1][1] == 1&& MatJV[1][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[2][0] == 1&& MatJV[2][1] == 1&& MatJV[2][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[0][0] == 1&& MatJV[1][0] == 1&& MatJV[2][0] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[0][1] == 1&& MatJV[1][1] == 1&& MatJV[2][1] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[0][2] == 1&& MatJV[1][2] == 1&& MatJV[2][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[0][0] == 1&& MatJV[1][1] == 1&& MatJV[2][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[2][0] == 1&& MatJV[1][1] == 1&& MatJV[0][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                
                if(MatJV[0][0] == 1&& MatJV[0][1] == 1&& MatJV[0][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[1][0] == 1&& MatJV[1][1] == 1&& MatJV[1][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[2][0] == 1&& MatJV[2][1] == 1&& MatJV[2][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[0][0] == 1&& MatJV[1][0] == 1&& MatJV[2][0] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[0][1] == 1&& MatJV[1][1] == 1&& MatJV[2][1] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[0][2] == 1&& MatJV[1][2] == 1&& MatJV[2][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[0][0] == 1&& MatJV[1][1] == 1&& MatJV[2][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[2][0] == 1&& MatJV[1][1] == 1&& MatJV[0][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
            
        } 
    }//GEN-LAST:event_Bot11ActionPerformed

    private void Bot12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot12ActionPerformed
    if(MatJV[0][1] == 0 && endgame == 0){
            if(userad != 0){           
                MatJV[0][1] = 1;
                Bot12.setText("X");
                user = user + 1;}
            if(userad == 0){
                MatJV[0][1] = 2;
                Bot12.setText("O");
                user++;}
            
                userad = user % 2;
            
                if(MatJV[0][0] == 1&& MatJV[0][1] == 1&& MatJV[0][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[1][0] == 1&& MatJV[1][1] == 1&& MatJV[1][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[2][0] == 1&& MatJV[2][1] == 1&& MatJV[2][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[0][0] == 1&& MatJV[1][0] == 1&& MatJV[2][0] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[0][1] == 1&& MatJV[1][1] == 1&& MatJV[2][1] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[0][2] == 1&& MatJV[1][2] == 1&& MatJV[2][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[0][0] == 1&& MatJV[1][1] == 1&& MatJV[2][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[2][0] == 1&& MatJV[1][1] == 1&& MatJV[0][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                
                if(MatJV[0][0] == 1&& MatJV[0][1] == 1&& MatJV[0][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[1][0] == 1&& MatJV[1][1] == 1&& MatJV[1][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[2][0] == 1&& MatJV[2][1] == 1&& MatJV[2][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[0][0] == 1&& MatJV[1][0] == 1&& MatJV[2][0] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[0][1] == 1&& MatJV[1][1] == 1&& MatJV[2][1] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[0][2] == 1&& MatJV[1][2] == 1&& MatJV[2][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[0][0] == 1&& MatJV[1][1] == 1&& MatJV[2][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[2][0] == 1&& MatJV[1][1] == 1&& MatJV[0][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_Bot12ActionPerformed

    private void Bot21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot21ActionPerformed
    if(MatJV[1][0] == 0 && endgame == 0){
            if(userad != 0){           
                MatJV[1][0] = 1;
                Bot21.setText("X");
                user++;}
            if(userad == 0){
                MatJV[1][0] = 2;
                Bot21.setText("O");
                user++;}
            
                userad = user % 2;
            
                if(MatJV[0][0] == 1&& MatJV[0][1] == 1&& MatJV[0][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[1][0] == 1&& MatJV[1][1] == 1&& MatJV[1][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[2][0] == 1&& MatJV[2][1] == 1&& MatJV[2][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[0][0] == 1&& MatJV[1][0] == 1&& MatJV[2][0] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[0][1] == 1&& MatJV[1][1] == 1&& MatJV[2][1] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[0][2] == 1&& MatJV[1][2] == 1&& MatJV[2][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[0][0] == 1&& MatJV[1][1] == 1&& MatJV[2][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[2][0] == 1&& MatJV[1][1] == 1&& MatJV[0][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                
                if(MatJV[0][0] == 1&& MatJV[0][1] == 1&& MatJV[0][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[1][0] == 1&& MatJV[1][1] == 1&& MatJV[1][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[2][0] == 1&& MatJV[2][1] == 1&& MatJV[2][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[0][0] == 1&& MatJV[1][0] == 1&& MatJV[2][0] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[0][1] == 1&& MatJV[1][1] == 1&& MatJV[2][1] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[0][2] == 1&& MatJV[1][2] == 1&& MatJV[2][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[0][0] == 1&& MatJV[1][1] == 1&& MatJV[2][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[2][0] == 1&& MatJV[1][1] == 1&& MatJV[0][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
        }        // TODO add your handling code here:
    }//GEN-LAST:event_Bot21ActionPerformed

    private void Bot22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot22ActionPerformed
    if(MatJV[1][1] == 0 && endgame == 0){
            if(userad != 0){           
                MatJV[1][1] = 1;
                Bot22.setText("X");
                user++;}
            if(userad == 0){
                MatJV[1][1] = 2;
                Bot22.setText("O");
                user++;}
            
                userad = user % 2;
            
                if(MatJV[0][0] == 1&& MatJV[0][1] == 1&& MatJV[0][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[1][0] == 1&& MatJV[1][1] == 1&& MatJV[1][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[2][0] == 1&& MatJV[2][1] == 1&& MatJV[2][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[0][0] == 1&& MatJV[1][0] == 1&& MatJV[2][0] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[0][1] == 1&& MatJV[1][1] == 1&& MatJV[2][1] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[0][2] == 1&& MatJV[1][2] == 1&& MatJV[2][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[0][0] == 1&& MatJV[1][1] == 1&& MatJV[2][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[2][0] == 1&& MatJV[1][1] == 1&& MatJV[0][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                
                if(MatJV[0][0] == 1&& MatJV[0][1] == 1&& MatJV[0][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[1][0] == 1&& MatJV[1][1] == 1&& MatJV[1][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[2][0] == 1&& MatJV[2][1] == 1&& MatJV[2][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[0][0] == 1&& MatJV[1][0] == 1&& MatJV[2][0] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[0][1] == 1&& MatJV[1][1] == 1&& MatJV[2][1] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[0][2] == 1&& MatJV[1][2] == 1&& MatJV[2][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[0][0] == 1&& MatJV[1][1] == 1&& MatJV[2][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[2][0] == 1&& MatJV[1][1] == 1&& MatJV[0][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_Bot22ActionPerformed

    private void Bot31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot31ActionPerformed
    if(MatJV[2][0] == 0 && endgame == 0){
            if(userad != 0){           
                MatJV[2][0] = 1;
                Bot31.setText("X");
                user++;}
            if(userad == 0){
                MatJV[2][0] = 2;
                Bot31.setText("O");
                user++;}
            
                userad = user % 2;
            
                if(MatJV[0][0] == 1&& MatJV[0][1] == 1&& MatJV[0][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[1][0] == 1&& MatJV[1][1] == 1&& MatJV[1][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[2][0] == 1&& MatJV[2][1] == 1&& MatJV[2][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[0][0] == 1&& MatJV[1][0] == 1&& MatJV[2][0] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[0][1] == 1&& MatJV[1][1] == 1&& MatJV[2][1] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[0][2] == 1&& MatJV[1][2] == 1&& MatJV[2][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[0][0] == 1&& MatJV[1][1] == 1&& MatJV[2][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[2][0] == 1&& MatJV[1][1] == 1&& MatJV[0][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                
                if(MatJV[0][0] == 1&& MatJV[0][1] == 1&& MatJV[0][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[1][0] == 1&& MatJV[1][1] == 1&& MatJV[1][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[2][0] == 1&& MatJV[2][1] == 1&& MatJV[2][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[0][0] == 1&& MatJV[1][0] == 1&& MatJV[2][0] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[0][1] == 1&& MatJV[1][1] == 1&& MatJV[2][1] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[0][2] == 1&& MatJV[1][2] == 1&& MatJV[2][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[0][0] == 1&& MatJV[1][1] == 1&& MatJV[2][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[2][0] == 1&& MatJV[1][1] == 1&& MatJV[0][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
        }        // TODO add your handling code here:
    }//GEN-LAST:event_Bot31ActionPerformed

    private void Bot32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Bot32ActionPerformed
    if(MatJV[2][1] == 0 && endgame == 0){
            if(userad != 0){           
                MatJV[2][1] = 1;
                Bot32.setText("X");
                user = user + 1;}
            if(userad == 0){
                MatJV[2][1] = 2;
                Bot32.setText("O");
                user = user + 1;
                aux = ""+userad;
                Saida.setText(aux);}
            
                userad = user % 2;
            
                if(MatJV[0][0] == 1&& MatJV[0][1] == 1&& MatJV[0][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[1][0] == 1&& MatJV[1][1] == 1&& MatJV[1][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[2][0] == 1&& MatJV[2][1] == 1&& MatJV[2][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[0][0] == 1&& MatJV[1][0] == 1&& MatJV[2][0] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[0][1] == 1&& MatJV[1][1] == 1&& MatJV[2][1] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[0][2] == 1&& MatJV[1][2] == 1&& MatJV[2][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[0][0] == 1&& MatJV[1][1] == 1&& MatJV[2][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                if(MatJV[2][0] == 1&& MatJV[1][1] == 1&& MatJV[0][2] == 1){
                    SaidaResultado.setText("Jogador 1 ganhou");endgame = 1;}
                
                if(MatJV[0][0] == 1&& MatJV[0][1] == 1&& MatJV[0][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[1][0] == 1&& MatJV[1][1] == 1&& MatJV[1][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[2][0] == 1&& MatJV[2][1] == 1&& MatJV[2][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[0][0] == 1&& MatJV[1][0] == 1&& MatJV[2][0] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[0][1] == 1&& MatJV[1][1] == 1&& MatJV[2][1] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[0][2] == 1&& MatJV[1][2] == 1&& MatJV[2][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[0][0] == 1&& MatJV[1][1] == 1&& MatJV[2][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
                if(MatJV[2][0] == 1&& MatJV[1][1] == 1&& MatJV[0][2] == 2){
                    SaidaResultado.setText("Jogador 2 ganhou");endgame = 1;}
            
        }        // TODO add your handling code here:
    }//GEN-LAST:event_Bot32ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaJogoVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaJogoVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaJogoVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaJogoVelha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaJogoVelha().setVisible(true);
            }
        });
    }

    int [][]MatJV =  new int[3][3];
    float user , userad;
    int c,endgame;
    String aux;
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bot11;
    private javax.swing.JButton Bot12;
    private javax.swing.JButton Bot13;
    private javax.swing.JButton Bot21;
    private javax.swing.JButton Bot22;
    private javax.swing.JButton Bot23;
    private javax.swing.JButton Bot31;
    private javax.swing.JButton Bot32;
    private javax.swing.JButton Bot33;
    private javax.swing.JLabel Saida;
    private javax.swing.JTextArea SaidaResultado;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
